const fs = require('node:fs');
const assert = require('node:assert/strict');
const code = fs.readFileSync('script.js', 'utf8');
assert.match(code, /Text="taodepzai"/);
assert.match(code, /✅ taodepzai v4\.67/);
assert.match(code, /local togBtn = New\("TextButton"/);
assert.match(code, /_G\.taodepzaiToggleImage/);
assert.match(code, /Name="GameToggleImage"/);
assert.match(code, /ScaleType=Enum\.ScaleType\.Crop/);
assert.match(code, /if toggleImage\.Visible then togBtn\.TextTransparency = 1 end/);
assert.match(code, /togBtn\.Activated:Connect/);
assert.match(code, /togBtn\.InputBegan:Connect/);
assert.match(code, /function Store\.load\(/);
assert.match(code, /local function RunCode\(/);
console.log('Static regression checks passed (Roblox runtime not available).');
